# Stage 1: Build the Angular application
FROM node:18 AS build

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies separately
COPY ./package*.json ./

# Install the Angular CLI globally
RUN npm install -g @angular/cli

# Install application dependencies
RUN npm ci

# Copy the rest of the application files
COPY . .

# Build the Angular application
RUN ng build --configuration=production

# Stage 2: Serve the Angular application
FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install the Angular CLI globally
RUN npm install -g @angular/cli

# Install application dependencies
RUN npm ci

# Copy the rest of the application files
COPY . .

# Expose the port that the Angular app will run on
EXPOSE 4200

# Command to run the Angular app
CMD ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
